// @generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
	getRecentLogs: () => __TAURI_INVOKE<LogEntry[]>("get_recent_logs"),
	getTelegramStatus: () => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("get_telegram_status")),
	connectTelegram: () => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("connect_telegram")),
	requestLoginCode: (phone: string) => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("request_login_code", { phone })),
	submitLoginCode: (code: string) => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("submit_login_code", { code })),
	submitPassword: (password: string) => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("submit_password", { password })),
	logout: () => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("logout")),
	listChats: (refresh: boolean) => typedError<ChatItem[], AppError>(__TAURI_INVOKE("list_chats", { refresh })),
	setChatWatched: (chatId: string, watched: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_chat_watched", { chatId, watched })),
	setGuestWatch: (enabled: boolean, query: string) => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("set_guest_watch", { enabled, query })),
	setChatDownloadTypes: (chatId: string, types: ChatDownloadTypes) => typedError<ChatDownloadTypes, AppError>(__TAURI_INVOKE("set_chat_download_types", { chatId, types })),
	setBackfillDays: (days: number) => typedError<number, AppError>(__TAURI_INVOKE("set_backfill_days", { days })),
	setChatBackfillDays: (chatId: string, days: number | null) => typedError<number, AppError>(__TAURI_INVOKE("set_chat_backfill_days", { chatId, days })),
	setChatAlias: (chatId: string, alias: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("set_chat_alias", { chatId, alias })),
	setShowMedia: (enabled: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_show_media", { enabled })),
	setProxy: (config: ProxyConfig_Deserialize) => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("set_proxy", { config })),
	setAutostart: (enabled: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_autostart", { enabled })),
	setDownloadConcurrency: (n: number) => typedError<number, AppError>(__TAURI_INVOKE("set_download_concurrency", { n })),
	setMinMediaMb: (n: number | null) => typedError<number | null, AppError>(__TAURI_INVOKE("set_min_media_mb", { n })),
	getDownloadStatus: () => __TAURI_INVOKE<DownloadProgress>("get_download_status"),
	setDownloadPaused: (paused: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_download_paused", { paused })),
	getIlinkStatus: () => __TAURI_INVOKE<IlinkStatus>("get_ilink_status"),
	ilinkStartLogin: () => typedError<IlinkStatus, AppError>(__TAURI_INVOKE("ilink_start_login")),
	ilinkLogout: () => typedError<IlinkStatus, AppError>(__TAURI_INVOKE("ilink_logout")),
	setIlinkNotifyEnabled: (enabled: boolean) => typedError<IlinkStatus, AppError>(__TAURI_INVOKE("set_ilink_notify_enabled", { enabled })),
	ilinkSendTest: () => typedError<IlinkStatus, AppError>(__TAURI_INVOKE("ilink_send_test")),
	cancelDownload: (fileId: string) => typedError<boolean, AppError>(__TAURI_INVOKE("cancel_download", { fileId })),
	listDownloads: () => typedError<DownloadItem[], AppError>(__TAURI_INVOKE("list_downloads")),
	getDownloadUsage: () => typedError<DownloadUsage, AppError>(__TAURI_INVOKE("get_download_usage")),
	listMessages: (chatId: string, query: string | null, beforeMessageId: number | null, limit: number | null) => typedError<MessagePage, AppError>(__TAURI_INVOKE("list_messages", { chatId, query, beforeMessageId, limit })),
	searchMessages: (query: string, cursor: {
	dateUnix: string,
	chatId: string,
	messageId: number,
} | null, limit: number | null) => typedError<MessagePage, AppError>(__TAURI_INVOKE("search_messages", { query, cursor, limit })),
	clearChatMessages: (chatId: string) => typedError<number, AppError>(__TAURI_INVOKE("clear_chat_messages", { chatId })),
	checkChatMedia: (chatId: string) => typedError<boolean, AppError>(__TAURI_INVOKE("check_chat_media", { chatId })),
	redownloadMessageMedia: (chatId: string, messageId: number) => typedError<boolean, AppError>(__TAURI_INVOKE("redownload_message_media", { chatId, messageId })),
	openUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_url", { url })),
	openPath: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("open_path", { path })),
	openDownloadDir: () => typedError<string, AppError>(__TAURI_INVOKE("open_download_dir")),
	pickDownloadDir: () => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("pick_download_dir")),
	setDownloadDir: (dir: string) => typedError<TelegramStatus_Serialize, AppError>(__TAURI_INVOKE("set_download_dir", { dir })),
	showMainWindow: () => __TAURI_INVOKE<void>("show_main_window"),
	hideMainWindow: () => __TAURI_INVOKE<void>("hide_main_window"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
};

/** Events */
export const events = {
	chatIngested: makeEvent<ChatIngested>("chat-ingested"),
	downloadProgress: makeEvent<DownloadProgress>("download-progress"),
	ilinkStatus: makeEvent<IlinkStatus>("ilink-status"),
	telegramStatusChanged: makeEvent<TelegramStatusChanged>("telegram-status-changed"),
};

/* Types */
export type AccountInfo = {
	name: string,
	username: string | null,
	phone: string | null,
};

export type ActiveDownload = {
	fileId: string,
	fileName: string,
	kind: MediaKind,
	bytes: string,
	total: string | null,
};

export type AppError = { kind: "Io"; message: string } | { kind: "Telegram"; message: string } | { kind: "Config"; message: string } | { kind: "Internal"; message: string };

export type AppInfo = {
	name: string,
	version: string,
	identifier: string,
};

/**  单个群组 / 频道要下载的类型。缺省全关。 */
export type ChatDownloadTypes = {
	video?: boolean,
	audio?: boolean,
	photo?: boolean,
	document?: boolean,
	text?: boolean,
};

export type ChatIngested = {
	chatId: string,
};

export type ChatItem = {
	id: string,
	kind: ChatKind,
	title: string,
	username: string | null,
	/**  是否在监听下载名单里。由 `list_chats` 根据 `settings.json` 填入。 */
	watched: boolean,
	types: ChatDownloadTypes,
	/**  有效回爬天数（覆盖或全局）。 */
	backfillDays: number,
	/**  该群单独设置的天数；`None` 表示跟全局。 */
	backfillDaysOverride: number | null,
	/**  本地别名；`None` 表示用 Telegram 原名。 */
	alias: string | null,
	/**  若这是频道评论组，对应的频道 id。 */
	commentOfId: string | null,
	/**  对应频道标题，列表副标题用。 */
	commentOfTitle: string | null,
	/**  若这是频道，关联讨论组 id。 */
	discussionId: string | null,
	/**  账号是否已加入该讨论组。没有评论组时为 `None`。 */
	discussionJoined: boolean | null,
	/**  未加入的公开预览槽位（全局最多一个）。 */
	guest?: boolean,
};

export type ChatKind = "group" | "channel" | "bot";

export type ChatUsage = {
	chatId: string | null,
	chatTitle: string | null,
	alias: string | null,
	bytes: string,
	kinds: KindUsage,
};

export type DownloadItem = {
	fileId: string,
	path: string,
	kind: MediaKind,
	size: string | null,
	chatId: string | null,
	chatTitle: string | null,
	alias: string | null,
	fileName: string,
	downloadedAt: string | null,
};

export type DownloadPhase = "idle" | "live" | "backfill" | "wait" | "floodWait" | "reconnect";

export type DownloadProgress = {
	phase: DownloadPhase,
	chatId: string | null,
	chatTitle: string | null,
	processed: number,
	downloaded: number,
	skipped: number,
	floodWaitSecs: number | null,
	detail: string | null,
	currentFile: string | null,
	currentKind: MediaKind | null,
	active: ActiveDownload[],
	queued: QueuedDownload[],
	paused: boolean,
};

export type DownloadUsage = {
	total: string,
	parts: string,
	kinds: KindUsage,
	chats: ChatUsage[],
};

/**  未加入公开群/频道预览。全局最多一个，与已加入监听并存。 */
export type GuestWatchStatus = {
	enabled: boolean,
	query: string,
	chatId: string | null,
	title: string | null,
	username: string | null,
};

export type IlinkQrState = "idle" | "wait" | "scanned" | "confirmed" | "expired";

export type IlinkStatus = {
	enabled: boolean,
	loggedIn: boolean,
	bound: boolean,
	qrUrl: string | null,
	qrState: IlinkQrState,
	lastError: string | null,
	boundUserHint: string | null,
};

export type KindUsage = {
	photo: string,
	video: string,
	audio: string,
	document: string,
	other: string,
};

/**  设置页展示的最近 warn / error。 */
export type LogEntry = {
	time: string,
	level: string,
	message: string,
};

export type LoginStep = "idle" | "needCode" | "needPassword" | "authorized";

/**  用户可勾选的落盘类型。语音算音频；贴纸不下。 */
export type MediaKind = "photo" | "video" | "document" | "audio";

export type MessageItem = {
	chatId: string,
	messageId: number,
	dateUnix: string,
	sender: string,
	text: string,
	mediaKind: string | null,
	mediaFileId: string | null,
	mediaPath: string | null,
	links: MessageLink[],
};

export type MessageLink = {
	offset: number,
	length: number,
	url: string,
};

export type MessagePage = {
	items: MessageItem[],
	hasMore: boolean,
};

/**  设置页展示 / 保存的 SOCKS5 代理。密码只在提交时出现，读回用 `hasPassword`。 */
export type ProxyConfig = ProxyConfig_Serialize | ProxyConfig_Deserialize;

/**  设置页展示 / 保存的 SOCKS5 代理。密码只在提交时出现，读回用 `hasPassword`。 */
export type ProxyConfig_Deserialize = {
	enabled: boolean,
	host?: string,
	port?: number,
	username?: string | null,
	password?: string | null,
	hasPassword?: boolean,
};

/**  设置页展示 / 保存的 SOCKS5 代理。密码只在提交时出现，读回用 `hasPassword`。 */
export type ProxyConfig_Serialize = {
	enabled: boolean,
	host: string,
	port: number,
	username: string | null,
	hasPassword: boolean,
};

export type QueuedDownload = {
	fileId: string,
	fileName: string,
	kind: MediaKind,
	chatId: string | null,
	messageId: number | null,
};

export type SearchCursor = {
	dateUnix: string,
	chatId: string,
	messageId: number,
};

export type TelegramStatus = TelegramStatus_Serialize | TelegramStatus_Deserialize;

export type TelegramStatusChanged = {
	connected: boolean,
	authorized: boolean,
};

export type TelegramStatus_Deserialize = {
	connected: boolean,
	authorized: boolean,
	sessionExists: boolean,
	loginStep: LoginStep,
	passwordHint: string | null,
	downloadDir: string,
	backfillDays: number,
	showMedia: boolean,
	downloadConcurrency: number,
	minMediaMb: number | null,
	autostart: boolean,
	account: AccountInfo | null,
	proxy: ProxyConfig_Deserialize,
	guestWatch: GuestWatchStatus,
};

export type TelegramStatus_Serialize = {
	connected: boolean,
	authorized: boolean,
	sessionExists: boolean,
	loginStep: LoginStep,
	passwordHint: string | null,
	downloadDir: string,
	backfillDays: number,
	showMedia: boolean,
	downloadConcurrency: number,
	minMediaMb: number | null,
	autostart: boolean,
	account: AccountInfo | null,
	proxy: ProxyConfig_Serialize,
	guestWatch: GuestWatchStatus,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

