mod commands;
mod error;
mod settings;
mod telegram;
mod tray;

use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};

use commands::{
    apply_autostart, cancel_download, clear_chat_messages, connect_telegram, get_app_info,
    get_download_status, get_download_usage, get_telegram_status, hide_main_window, list_chats,
    list_downloads, list_messages, logout, open_download_dir, open_path, open_url,
    pick_download_dir, quit_app, request_login_code, search_messages, set_autostart,
    set_backfill_days, set_chat_alias, set_chat_backfill_days, set_chat_download_types,
    set_chat_watched, set_download_concurrency, set_download_paused, set_show_media,
    show_main_window, submit_login_code, submit_password,
};
use settings::{AppSettings, ChatDownloadTypes};
use telegram::{
    load_dotenv, AccountInfo, ActiveDownload, ChatIngested, ChatItem, ChatKind, DownloadPhase,
    DownloadProgress, LoginStep, MediaKind, SessionPaths, SyncHandle, TelegramHandle,
    TelegramStatusChanged,
};

pub struct AppState {
    pub telegram: tokio::sync::Mutex<TelegramHandle>,
    pub sync: SyncHandle,
}

fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            get_app_info,
            get_telegram_status,
            connect_telegram,
            request_login_code,
            submit_login_code,
            submit_password,
            logout,
            list_chats,
            set_chat_watched,
            set_chat_download_types,
            set_backfill_days,
            set_chat_backfill_days,
            set_chat_alias,
            set_show_media,
            set_autostart,
            set_download_concurrency,
            get_download_status,
            set_download_paused,
            cancel_download,
            list_downloads,
            get_download_usage,
            list_messages,
            search_messages,
            clear_chat_messages,
            open_url,
            open_path,
            open_download_dir,
            pick_download_dir,
            show_main_window,
            hide_main_window,
            quit_app
        ])
        .events(collect_events![
            TelegramStatusChanged,
            DownloadProgress,
            ChatIngested
        ])
        .typ::<MediaKind>()
        .typ::<ChatItem>()
        .typ::<ChatKind>()
        .typ::<LoginStep>()
        .typ::<AccountInfo>()
        .typ::<ChatDownloadTypes>()
        .typ::<DownloadPhase>()
        .typ::<ActiveDownload>()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    load_dotenv();

    let specta = specta_builder();

    #[cfg(debug_assertions)]
    specta
        .export(
            Typescript::default().header("// @generated by tauri-specta. Do not edit.\n"),
            "../src/lib/bindings.ts",
        )
        .expect("failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            tray::show_window(app);
        }))
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec!["--hidden"]),
        ))
        .plugin(
            tauri_plugin_log::Builder::new()
                .level(log::LevelFilter::Info)
                .build(),
        )
        .manage(AppState {
            telegram: tokio::sync::Mutex::new(TelegramHandle::new()),
            sync: SyncHandle::new(),
        })
        .invoke_handler(specta.invoke_handler())
        .setup(move |app| {
            specta.mount_events(app);
            tray::setup(app)?;

            if let Ok(paths) = SessionPaths::resolve(app.handle()) {
                if let Err(err) = paths.ensure_dirs() {
                    log::warn!("failed to create telegram data dirs: {err}");
                }
                paths.allow_asset_access(app.handle());
                let settings = AppSettings::load(&paths.root);
                if let Err(err) = apply_autostart(app.handle(), settings.autostart) {
                    log::warn!("failed to apply autostart: {err}");
                }
                app.handle()
                    .state::<AppState>()
                    .sync
                    .set_paused(settings.download_paused);
            }

            if std::env::args().any(|arg| arg == "--hidden") {
                tray::hide_window(app.handle());
            }

            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let _ = window.hide();
                api.prevent_close();
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_typescript_bindings() {
        specta_builder()
            .export(
                Typescript::default().header("// @generated by tauri-specta. Do not edit.\n"),
                "../src/lib/bindings.ts",
            )
            .expect("failed to export typescript bindings");
    }
}
